### ISSUE TITLE
autoreconf: 'configure.ac' or configure.in' is required

### ISSUE THREAD

**Issue by polarathene** [egorovli/mozjpeg-docker#1]
Tried building your image and got the following error:

```
Step 4/18 : RUN git clone git://github.com/mozilla/mozjpeg.git ./
 ---> Running in 068f7f98f029
Cloning into '.'...
Removing intermediate container 068f7f98f029
 ---> eae5baf7055a
Step 5/18 : RUN autoreconf -fiv   && ./configure   && make install prefix=/usr/local libdir=/usr/local/lib64
 ---> Running in d330155a9d4c
autoreconf: 'configure.ac' or 'configure.in' is required
The command '/bin/sh -c autoreconf -fiv   && ./configure   && make install prefix=/usr/local libdir=/usr/local/lib64' returned a non-zero code: 1
```

**Comment by polarathene** [comment]
Problem appears to be due to [a recent switch to cmake](https://github.com/mozilla/mozjpeg/issues/314).

I got it working again with the following changes:

```Dockerfile
RUN apk --update --no-cache add \
  build-base \
  cmake \
  git \
  libtool \
  nasm

# ...

RUN mkdir _build \
  && cd _build \
  && cmake -G"Unix Makefiles" -DCMAKE_INSTALL_PREFIX=/usr/local -DCMAKE_INSTALL_LIBDIR=/usr/local/lib64 .. \
  && make
```

I'm pretty sure the mkdir/cd instructions should be something else, `WORKDIR` covers both? It's 3am so I'm going to get some rest, I can send a PR after that :)

**Comment by egorovli** [comment]
Thanks! I've also fixed the source dir for cmake call in bcfb588219ab640ccc15fb5c2ee3d6c412776fd5.

**Comment by polarathene** [comment]
@egorovli oh, sorry about that! I had an extra WORKDIR command for `_build/` subdirectory hence the `..`. I was just basing that on what I had seen for the syntax usage, if it's not important that's fine :)

Would you happen to know how to enable PNG support? It might have been automatic before switching to CMake if libpng was available? There is an [issue open on mozjpeg repo about it](https://github.com/mozilla/mozjpeg/issues/144#issuecomment-451812140).

**Comment by egorovli** [comment]
Unfortunately, no. I've used this image to provide `mozjpeg` binaries for an HTTP microservice, but since then I've switched to [imazen/imageflow](https://github.com/imazen/imageflow) if I need on-the-fly image processing _or_ [gatsby](https://github.com/gatsbyjs/gatsby) with [gatsby-plugin-sharp](https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-plugin-sharp) if I need static (build-time processed) images.
